export const TASKS_ADD = 'TASKS_ADD';
export const TASKS_REMOVE = 'TASKS_REMOVE';
export const TASKS_COMPLETE = 'TASKS_COMPLETE';
export const TASKS_OPEN_EDIT_MODAL = 'TASKS_OPEN_EDIT_MODAL';
export const TASKS_OPEN_ADD_MODAL = 'TASKS_OPEN_ADD_MODAL';
export const TASKS_CLOSE_MODAL = 'TASKS_CLOSE_MODAL';
export const TASKS_EDIT = 'TASKS_EDIT';
export const TASKS_CHANGE_ORDER = 'TASKS_CHANGE_ORDER';
